### ISSUE TITLE
sample data

### ISSUE THREAD

**Issue by rumcode** [tfgm/sbedecoder#10]
Hi, this is not really an issue, but I'm not sure where to place the question. 

Could you post some data or a a http link to sbe data that you know works with your program? I would like to step through it, but the data I have, as you pointed out is not in sbe format, although it is from the CME.

Just a meg or two would be nice.

Thanks in advance.

**Comment by tfgm-bud** [comment]
I'll check with the CME to see if I can post some sample data.  In the meantime, I found this:

https://www.nanotick.com/sample

The guys at nanotick are great to work with.  The will provide you with an ERF capture of some CME data.  ERF is slightly different than PCAP but it is pretty straightforward to convert it with editcap:

```
editcap -F libpcap -T ether erf-ethernet-example.erf erf-ethernet-example.pcap 
```
[thanks to http://www.netresec.com/?page=Blog&month=2012-11&post=Convert-Endace-ERF-capture-files-to-PCAP]

After you convert it, the sbedecoder will be able to decode it.  

There is a way to directly parse ERF files with python but it involves python libtrace (https://www.cs.auckland.ac.nz/~nevil/python-libtrace/) which isn't in pypy so it is a little more difficult to setup than dpkt hence I didn't use it with the sbedecoder.
