### ISSUE TITLE
Question about CME Market Depth data

### ISSUE THREAD

**Issue by stokhos** [tfgm/sbedecoder#11]
Hi
I'm looking for something to decode CME Market Depth data. I found your programs. I found one closed issue about invalid tcpdump header. Do you have plan to include parser for CME market depth data? If you do I would like to help.
Best

**Comment by tfgm-bud** [comment]
@stokhos Thanks for your note.  The decoder (`mdp_decoder.py`) will currently decode CME Market by Order (MBO) packets just fine.  Unfortunately, the book builder (`mdp_book_builder.py`) only handles CME Market by Price (MBP) right now.

I'd love to have support for CME MBO.  We haven't really had time to look at it yet and nothing is pending.  If you'd like to contribute, we'd be happy to incorporate your code if you want to fork and submit a pull request  If you have any questions, I'm happy to answer.

**Comment by stokhos** [comment]
@tfgm-bud Hi I looked at the cme ftp, but I couldn't find the template for market depth. Do you know any other places that I might find the template?
Best

**Comment by tfgm-bud** [comment]
Have a look around on sftpng.cmegroup.com: https://www.cmegroup.com/confluence/plugins/servlet/mobile?contentId=81362961#iLinkArchitecture-SFTP-MSGWConfiguration
