### ISSUE TITLE
is_string_type fails with null strings

### ISSUE THREAD

**Issue by tamboril** [tfgm/sbedecoder#19]
It's still problematic to base `is_string_type` on the field's `semantic_type`.
Though #17 fixes single-character strings, there is an issue with integral
types having semantic type of `String` (e.g. SecurityID and OrderID).

The `value` property tries to split a raw integral value on its null bytes as
if it were a string.

I'll follow up with a pull request shortly.

**Comment by tfgm-bud** [comment]
@tamboril Thanks for all your improvements!

**Comment by tamboril** [comment]
Bud,  

No problem.  It's a good library.  And with these changes, I have replaced my C++ prettyprinter with just a few lines of python.

I'm done with changes for awhile.  I hope you or someone else has time to get versioning support in there.

**Comment by tamboril** [comment]
FYI, I'm working on versioning support.  Expect a PR soon.
