### ISSUE TITLE
Make sbedecoder publicly available on pypi.org

### ISSUE THREAD

**Issue by ryanohnemus** [tfgm/sbedecoder#31]
You can currently use `pip install git+https://github.com/tfgm/sbedecoder` to pip install the sbedecoder package, but it would be great if this could be uploaded to pypi.org. It would also help with project visibility as a lot of people can easily search through their web ui for this type of package.

Thank you!

**Comment by tfgm-bud** [comment]
Done with release 0.1.5 (75cb78f)

**Comment by tfgm-bud** [comment]
https://pypi.org/project/sbedecoder/

**Comment by tfgm-bud** [comment]
NP.  Hopefully it will increase visibility.
